import { useState, useEffect } from 'react'
import './App.css'
import { BrowserRouter, Route, Routes, Link, useParams } from "react-router-dom";

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/index.html" element={<Index />} />
        <Route path="/lists" element={<Lists />} />
        <Route path="/elim/:list_name" element={<Elim />} />
        <Route path='/swiss_pair/:list_name' element={<Swiss_Pair />} />
        <Route path='/edit_players/:list_name' element={<Edit_Players />} />
        <Route path="*" element={<Not_Found />} />
      </Routes>
    </BrowserRouter>
  );
}

//this is in the source folder
// before accessing lists, get token
// use effect
// access token generated by flask when the user logs in
// plug in the username to generate token

function Index() {
  return (
    <>
      <h1>Login</h1>
      <div>
        <form method="POST" action="/create_account">
          <p>
            <label htmlFor="username">Username:</label>
            <input type="text" id="username" name="username" required />
          </p>
          <p>
            <label htmlFor="password">Password:</label>
            <input type="text" id="password" name="password" required />
          </p>
          <Link to="/lists"> <input type="submit" value="Create Account" name="submit" id="submit" /> </Link>
        </form>
      </div>
    </>
  );
}

function Lists() {
  let [list, set_list] = useState('');
  //let swiss_setup_request = "/swiss_setup/" + list;
  let swiss_pair_link = "/swiss_pair/" + list;
  let elim_link = "/elim/" + list;
  let edit_players_link = "/edit_players/" + list;
  let request_url = "/groups";
  let [html, set_html] = useState("");
  let [groups, set_groups] = useState({});

  useEffect(() => {
    set_html("");
    async function x() {
      set_groups(await get_data(request_url))
    }
    x()
  }, []);

  //useEffect(() => {
  for (let group in groups) {
    html += `<option value=${group}>${group}</option>`;
  }
  //}, []);

  return (
    <>
      <h1>User Lists</h1>
      <div>
        <p>Select a list to make a bracket for:</p>
        <select name="user_lists" id="user_lists" onChange={(e) => set_list(e.target.value)}>
          <option value="standard_list">Select a List</option>
          <div dangerouslySetInnerHTML={{ __html: html }} />
        </select>
        <Link to={swiss_pair_link}> <input type="submit" value="Create Swiss Pairing" name="submit" /> </Link>
        <Link to={elim_link}> <input type="submit" value="Create Elimination Bracket" name="submit" /> </Link>
        <Link to={edit_players_link}> <input type="submit" value="Edit Players" name="submit" /></Link>
      </div>
    </>
  );
}

function Elim() {
  let { list_name } = useParams();
  let request_url = "/players/" + list_name;
  let [players, setPlayers] = useState({});

  useEffect(() => {
    async function x() {
      setPlayers(await get_data(request_url));
    }
    x();
  }, []);

  let num_players = Object.keys(players).length
  let num_players_temp = num_players
  let html = `<div id = "players">`
  
  html+=`<div id = "col0">`
  for(let i=0; i<num_players;i++) {
    html+=`<div><input type="text" value="${Object.keys(players).at(i)}"/></div>`
  }

  if(num_players%2 != 0) {
    html+=`<div><input type="text" value="No Player"/></div>`
    num_players_temp++;
  }
  html+=`</div>`

  let count = 1;
  while(num_players_temp > 1){
    num_players_temp = Math.ceil(num_players_temp/2)
    html+=`<div id=col${count}>`
    for(let i=0; i<num_players_temp;i++) {
      html+=`<div><input type="text"/></div>`
    }
    html+=`</div>`
    count++;
  }

  html += `</div>`

  return (
    <>
      <h1>Elimination Bracket</h1>
      <div dangerouslySetInnerHTML={{ __html: html }} />
    </>
  );
}

function Not_Found() {
  return (
    <>
      <h1>Page Not Found</h1>
      <div>
        <p>Did you meant to go to any of these pages?</p>
        <nav>
          <ul>
            <li>
              <Link to="/index">Login Page</Link>
            </li>
            <li>
              <Link to="/lists">List Page</Link>
            </li>
          </ul>
        </nav>
      </div>
    </>
  );
}

async function get_data(data_request) {
  try {
    let response = await fetch(data_request, {
      method: 'GET'
    })
    let responseData = await response.json();
    return responseData
  }
  catch (ex) {
    console.error(ex)
  }
}

async function rr_next_round(round_request) {
  try {
    let response = await fetch(round_request, {
      method: 'GET'
    })
    let responseData = await response.json();
    return responseData
  }
  catch (ex) {
    console.error(ex)
  }
}

function update_data(round_request, round) {
  return rr_next_round(round_request, round)
}

async function edit_player(list_name, player, rank, type) {
  let request = "/edit_player/" + list_name;
  let formData = new FormData();
  formData.append("player", player);
  formData.append("rank", rank);
  try {
    await fetch(request,
      {
        method: type,
        body: formData
      });
  }
  catch (ex) {
    console.error(ex);
  }
}

function Edit_Players() {
  let [player, setPlayer] = useState("");
  let [rank, setRank] = useState("");
  let [playerList, setplayerList] = useState([]);
  let [data, set_data] = useState('');
  let { list_name } = useParams();
  let data_request = "/players/" + list_name;

  useEffect(() => {
    async function x() {
      set_data(await get_data(data_request));
    }
    x();
  }, []);

  useEffect(() => {
    if (data != {}) {
      for (let player in data) {
        preAddItem(player, data[player]);
      }
    }
  }, [data]);

  function preAddItem(player, rank) {
    let newItem = {
      key: player,
      text: player + " (" + rank + ")"
    };

    setplayerList(prevList => [...prevList, newItem]);
  }

  async function addItem(event) {
    event.preventDefault();

    if (player.trim() !== "") {
      let newItem = {
        key: player,
        text: player + " (" + rank + ")"
      };

      let temp_player = player;
      let temp_rank = rank;
      await edit_player(list_name, temp_player, temp_rank, "POST");

      setplayerList(prevList => [...prevList, newItem]);
      setPlayer("");
      setRank("");
    }

    event.target.player.focus();
    event.target.rank.focus();
  }

  async function deleteItem(key) {
    setplayerList(prevList => prevList.filter(
      item => item.key !== key));
    await edit_player(list_name, key, rank, "DELETE");
  }

  return (
    <>
      <h1>player List</h1>
      <form onSubmit={addItem}>
        <label htmlFor="player">Player?</label>&nbsp;
        <input id="player" type="text" autoFocus
          value={player} onChange={(e) => setPlayer(e.target.value)} />
        <label htmlFor="rank">Rank?</label>&nbsp;
        <input id="rank" type="text" autoFocus
          value={rank} onChange={(e) => setRank(e.target.value)} />
        &nbsp;
        <button type="submit">Add</button>
      </form>
      <PlayerList List={playerList}
        delete={deleteItem} />
    </>
  );
}

function PlayerList(props) {

  const PlayerList = props.List;

  return (
    <ol>
      {PlayerList.map((item) =>
        <li key={item.key}>
          {item.text} &nbsp;
          <button onClick={() => props.delete(item.key)}>
            X
          </button>
        </li>
      )}
    </ol>
  );
}

function Swiss_Pair() {
  let { list_name } = useParams();
  let data_request = "/swiss_setup/" + list_name
  let [data, set_data] = useState('');
  let player_table = ''
  let [round_number, set_round_number] = useState(0)


  useEffect(() => {
    set_round_number(1);
    async function x() {
      set_data(await get_data(data_request))
      await button_listener()
    }
    x()
  }, []);

  async function button_listener() {
    let button = document.getElementById("next_round")
    button.addEventListener("click", async function x() {
      set_round_number(round_number += 1)
      round_request = "/rr_next_round/" + list_name + "/" + round_number;
      set_data(await update_data(round_request, round_number))
    })
  }

  let round_request = "/rr_next_round/" + list_name + "/" + round_number;
  if (data != {}) {
    player_table = "<table><tr><th>White</th><th>Black</th></tr>";
    for (let player in data) {
      player_table += `<tr><td>${player}</td><td>${data[player]}</td></tr>`;
    }
    player_table += "</table>"
  }

  return (
    <>
      <h1>Swiss Pairing Bracket: {list_name}</h1>
      <div>
        <p>
          <div dangerouslySetInnerHTML={{ __html: player_table }} />
        </p>
      </div>
      <div>
        <button id='next_round'>
          Next Round
        </button>
      </div>
    </>
  )
}

export default App;